spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://cs.neiu.edu/${DB_NAME}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql

cloud:
  name: ${CLOUD_NAME}
  secret: ${CLOUD_SECRET}
  key: ${CLOUD_KEY}

server:
  error:
    whitelabel:
      enabled: false